### PR TITLE
Sdaves port to 0.18.0

### PR DESCRIPTION
**Pull request by sdaves**
Hello. I had to make these changes to get Updater working in my 0.18.0 project. Let me know if you are interested in merging them.

Thanks!

### CODE REVIEW

**Comment by mpdairy** [comment]
Hey thanks a lot!

**Comment by mpdairy** [comment]
@sdaves I merged your updates and I updated the examples last night, then bumped it with `elm-package bump`, but it's still not updated on the repository. Do you know if I have to do anything else, or does it just take a while?

**Comment by sdaves** [comment]
Tag a new version and push it with git push --tags

**Comment by mpdairy** [comment]
@sdaves do I have to do anything after git push --tags? I made a new 1.0.1 tag and pushed it, but elm-packages still shows the old one.

**Comment by sdaves** [comment]
https://github.com/mpdairy/elm-component-updater/blob/master/elm-package.json#L2

Needs to be 1.0.1

**Comment by sdaves** [comment]
git tag -a 1.0.1 -m "0.18 upgrade"
git push --tags
elm-package publish

**Comment by mpdairy** [comment]
Ok, thanks, I just forgot the `elm-package publish` part

**Pull request merged**
